version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      
  pre_build:
    commands:
      - echo "Setting up environment variables based on branch..."
      - if [[ "$CODEBUILD_WEBHOOK_HEAD_REF" == "refs/heads/qa" ]]; then
          export ENV_FOLDER="environment/qa";
          export TF_VAR_env="qa";
        elif [[ "$CODEBUILD_WEBHOOK_HEAD_REF" == "refs/heads/prod" ]]; then
          export ENV_FOLDER="environment/prod";
          export TF_VAR_env="prod";
        else
          echo "Branch not recognized. Exiting.";
          exit 1;
        fi

  build:
    commands:
      - echo "Running Terraform Init..."
      - cd $ENV_FOLDER
      - terraform init
      - echo "Running Terraform Plan for $TF_VAR_env environment..."
      - terraform plan -out=tfplan
      
  post_build:
    commands:
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan

  # build:
  #   commands:
  #     - echo "Running terraform in environment/prod"
  #     - cd environment/prod
  #     - terraform init
  #     - terraform plan -out=tfplan-prod
  #     # - terraform apply "tfplan-prod"
  #     - cd ../..

  #     - echo "Running terraform in environment/qa"
  #     - cd environment/qa
  #     - terraform init
  #     - terraform plan -out=tfplan-qa
  #     # - terraform apply "tfplan-qa"
  #     - cd ../..

  #     - echo "Running terraform in infrastructure"
  #     - cd infrastructure
  #     - terraform init
  #     - terraform plan -out=tfplan-infra
  #     # - terraform apply "tfplan-infra"
  #     - cd ..

artifacts:
  files:
    - "**/*"
