version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      
  pre_build:
    commands:
      - echo "Setting up qa environment"
      - echo "Building project for branch:$CODEPIPELINE_ENV"

  build:
    commands:
      - echo "Running Terraform in qa"
      - cd environment/qa
      - terraform init
      - terraform plan -out=tfplanqa
      # - terraform apply "tfplanqa"
      - cd ../..

      - echo "Running terraform in infrastructure"
      - cd infrastructure
      - terraform init
      - terraform plan -out=tfplan-infra
      # - terraform apply "tfplan-infra"
      - cd ..

artifacts:
  files:
    - "**/*"
