version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      
  pre_build:
    commands:
      - echo "Building project for branch:$ENV"

  build:
    commands:
      - |
        if [[ "$ENV" == "qa" ]] || [[ "$ENV" == "prod" ]]; then
          echo "Switching to environment folder:$ENV"
          cd environment/$ENV
          terraform init
          terraform init -backend-config="bucket=prod-house-terraform-i" -backend-config="key=infinitum360/v1/environment/$ENV/state" -backend-config="region=ap-south-1"
          terraform plan -out=tfplan$ENV
          terraform apply "tfplan$ENV"
        elif [[ "$ENV" == "infrastructure" ]]; then
          echo "Switching to infrastructure folder"
          cd infrastructure
          terraform init -backend-config="bucket=prod-house-terraform-i" -backend-config="key=infinitum360/v1/infrastructure/state" -backend-config="region=ap-south-1"
          terraform plan -out=tfplan-infra
          terraform apply "tfplan-infra"
        else
          echo "Error:Invalid environment specified in ENV variable. Exiting."
          exit 1
        fi

artifacts:
  files:
    - "**/*"
