version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.3.1/terraform_1.3.1_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin
      - chmod +x /usr/local/bin/terraform
  pre_build:
    commands:
      - echo "Loading environment variables..."
      - source build.env
  build:
    commands:
      - echo "Running terraform init and plan in $TARGET_DIR"
      - cd $CODEBUILD_SRC_DIR/$TARGET_DIR
      - terraform init -backend-config="bucket=<your-terraform-state-bucket>"
      - terraform plan -out=tfplan
artifacts:
  files:
    - $TARGET_DIR/tfplan
